### ISSUE TITLE
InquiryActivity crashing while persona server down.

### ISSUE THREAD

**Issue by bhuvan0616** [persona-id/persona-android-sdk#48]
Crash happing in InquiryActivity when the persona server is down. 

Expected behaviour:
 If the persona server is down. That should be notified through `InquiryResponse.Error`. 

**Stacktrace**
```
Fatal Exception: f7.a: Expected BEGIN_OBJECT but was NUMBER at path $
       at com.squareup.moshi.JsonUtf8Reader.beginObject(JsonUtf8Reader.java:172)
       at com.withpersona.sdk2.inquiry.network.ErrorResponseJsonAdapter.fromJson(ErrorResponseJsonAdapter.kt:35)
       at com.withpersona.sdk2.inquiry.network.ErrorResponseJsonAdapter.fromJson(ErrorResponseJsonAdapter.kt:21)
       at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
       at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:58)
       at com.withpersona.sdk2.inquiry.internal.CreateInquiryWorker$run$1.invokeSuspend(CreateInquiryWorker.kt:47)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7660)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
**Device Details**
Brand: Google
Model: Pixel 3 XL
Orientation: Portrait
RAM free: 980.66 MB
Disk free: 21.46 GB
Operating system
Version: Android 11
Orientation: Portrait
Rooted: No

**Comment by SalvatoreT** [comment]
Thank you for the report! We're working on a fix. 👍🏼
