### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by talaikis** [persona-id/persona-android-sdk#54]
```
ConcurrentModificationException: None at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441) at java.util.HashMap$KeyIterator.next(HashMap.java:1465) at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:13) at com.airbnb.lottie.LottieAnimationView$b.b(LottieAnimationView.java:1) at com.airbnb.lottie.LottieAnimationView$b.a(LottieAnimationView.java:1)
```

with

```
react-native: 0.68.2
react-native-persona: 2.2.9
```

**Comment by SalvatoreT** [comment]
Hey @talaikis, we have a fix on the underlying Android issue and just shipped it with the `react-native-persona` version `2.2.10`. Can you please update and give it a go? I believe that should address your issue.
