### ISSUE TITLE
[Bug] Persona returning a 406 response on Android devices

### ISSUE THREAD

**Issue by ff-adrian-obando** [persona-id/persona-android-sdk#66]
Hello,
Our Sentry is reporting the following error:
` java.lang.RuntimeException: Unable to parse error response. Error code: 406
    at com.withpersona.sdk2.inquiry.internal.CreateInquiryWorker$run$1.invokeSuspend(CreateInquiryWorker.kt:52)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:233)
    at android.app.ActivityThread.main(ActivityThread.java:8063)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)`
It seems for specific devices the persona server it's not accepting the request and returning this error causing a crash on the app. The 406 error appears to be related to the headers with which the SDK sends the request.

Here's a list of  devices that are reporting the issue:

- motorola one 5G ace
- Samsumg Galaxy A12  
- Samsung Galaxy Note 8
- moto g pure
- ONEPLUS NORD N100

**Comment by idunnololz** [comment]
This should have been fixed in version 2.2.20 of the SDK. We highly recommend updating to the latest SDK (2.2.29 at the time of writing) as we have rolled out a number of stability patches recently which should reduce the how often users crash.

**Comment by ff-adrian-obando** [comment]
Thank you for the quick response! I'll update the library and reopen the issue if the error persists.
