### ISSUE TITLE
[Bug] Autocomplete input crashes the app on Android

### ISSUE THREAD

**Issue by ff-adrian-obando** [persona-id/persona-android-sdk#67]
We are getting reports that the autocomplete input on the persona form is crashing on some Android devices with the following error:
`java.util.ConcurrentModificationException: null
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
    at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
    at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:605)
    at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:85)
    at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:83)
    at com.airbnb.lottie.LottieTask.notifySuccessListeners(LottieTask.java:148)
    at com.airbnb.lottie.LottieTask.access$100(LottieTask.java:28)
    at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:135)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7386)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)`
the issue seems to happen at some point when the user uses the autocomplete address feature on the persona form.

**Comment by daniel-e-gonzalez** [comment]
Hi @ff-adrian-obando, what version of the android sdk are you seeing this issue on? This problem should be fixed in the latest version of the sdk.

**Comment by daniel-e-gonzalez** [comment]
Specifically, version 2.2.17 and later should not have this problem.

**Comment by daniel-e-gonzalez** [comment]
Ok, sounds good! Please let us know if you are still having the same issue after updating.
