### ISSUE TITLE
Crash with missing renderscript - older devices

### ISSUE THREAD

**Issue by chad-cmb** [persona-id/persona-android-sdk#94]
We see a small spike in crashes with Android 8 devices over the weekend.

Here is the stacktrace - appears to be missing the renderscipt library on these devices?

Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.coffeemeetsbagel-EFE3w2JcdZFDgI9CXvbc6g==/base.apk"],nativeLibraryDirectories=[/data/app/com.coffeemeetsbagel-EFE3w2JcdZFDgI9CXvbc6g==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "librenderscript-toolkit.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
       at java.lang.System.loadLibrary(System.java:1667)
       at com.google.android.renderscript.Toolkit.<clinit>(Toolkit.kt:1093)
       at com.withpersona.sdk2.camera.analyzers.BarcodePdf417Analyzer.sharpenImage(BarcodePdf417Analyzer.kt)
       at com.withpersona.sdk2.camera.analyzers.BarcodePdf417Analyzer.analyze-IoAF18A(BarcodePdf417Analyzer.kt:37)
       at com.withpersona.sdk2.camera.GovernmentIdFeed.analyze(GovernmentIdFeed.kt:52)
       at androidx.camera.core.ImageAnalysis.lambda$setAnalyzer$2(ImageAnalysis.java)
       at androidx.camera.core.ImageAnalysisAbstractAnalyzer.lambda$analyzeImage$0(ImageAnalysisAbstractAnalyzer.java:285)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

**Comment by chad-cmb** [comment]
Opened in the wrong repo.
