### ISSUE TITLE
App crashes in production on version 2.8.0 

### ISSUE THREAD

**Issue by empowerDan** [persona-id/persona-android-sdk#98]
Fatal Exception: java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
       at retrofit2.HttpServiceMethod.parseAnnotations(HttpServiceMethod.java:46)
       at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:39)
       at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202)
       at retrofit2.Retrofit$1.invoke(Retrofit.java:160)
       at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
       at $Proxy11.d()
       at com.withpersona.sdk2.inquiry.internal.CreateInquiryWorker$run$1.invokeSuspend(CreateInquiryWorker.kt:54)
       at com.withpersona.sdk2.inquiry.internal.CreateInquiryWorker$run$1.invoke(CreateInquiryWorker.kt:1)
       at com.withpersona.sdk2.inquiry.internal.CreateInquiryWorker$run$1.invoke(CreateInquiryWorker.kt:1)
       at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
       at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
       at com.squareup.workflow1.Workflows__SinkKt.collectToSink(Sink.kt:103)
       at com.squareup.workflow1.Workflows.collectToSink(Workflows.java:1)
       at com.squareup.workflow1.Workflows__WorkerWorkflowKt$runWorker$2.invokeSuspend(WorkerWorkflow.kt:78)
       at com.squareup.workflow1.Workflows__WorkerWorkflowKt$runWorker$2.invoke(WorkerWorkflow.kt:1)
       at com.squareup.workflow1.Workflows__WorkerWorkflowKt$runWorker$2.invoke(WorkerWorkflow.kt:1)
       at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
       at kotlinx.coroutines.BuildersKt.withContext(Builders.kt:1)
       at com.squareup.workflow1.Workflows__WorkerWorkflowKt.runWorker(WorkerWorkflow.kt:76)
       at com.squareup.workflow1.Workflows.runWorker(Workflows.java:1)
       at com.squareup.workflow1.WorkerWorkflow$render$1.invokeSuspend(WorkerWorkflow.kt:57)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:365)
       at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith$default(DispatchedContinuation.kt:276)
       at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:39)
       at kotlinx.coroutines.LazyStandaloneCoroutine.onStart(Builders.common.kt:206)
       at kotlinx.coroutines.JobSupport.startInternal(JobSupport.kt:397)
       at kotlinx.coroutines.JobSupport.start(JobSupport.kt:381)
       at com.squareup.workflow1.internal.WorkflowNode.renderWithStateType(WorkflowNode.kt:195)
       at com.squareup.workflow1.internal.WorkflowNode.render(WorkflowNode.kt:103)
       at com.squareup.workflow1.internal.WorkflowChildNode.render(WorkflowChildNode.kt:55)
       at com.squareup.workflow1.internal.SubtreeManager.render(SubtreeManager.kt:130)
       at com.squareup.workflow1.internal.RealRenderContext.renderChild(RealRenderContext.kt:61)
       at com.squareup.workflow1.StatefulWorkflow$RenderContext.renderChild(StatefulWorkflow.kt:1)
       at com.squareup.workflow1.Workflows__BaseRenderContextKt.runningWorker(BaseRenderContext.kt:307)
       at com.squareup.workflow1.Workflows.runningWorker(Workflows.java:1)
       at com.squareup.workflow1.Workflows__BaseRenderContextKt.runningWorker(Workflows__BaseRenderContext.kt:286)
       at com.withpersona.sdk2.inquiry.internal.InquiryWorkflow.renderCreateInquiryFromTemplate(InquiryWorkflow.kt:267)
       at com.withpersona.sdk2.inquiry.internal.InquiryWorkflow.render(InquiryWorkflow.kt:117)
       at com.withpersona.sdk2.inquiry.internal.InquiryWorkflow.access$resyncState(InquiryWorkflow.kt:43)
       at com.withpersona.sdk2.inquiry.internal.InquiryWorkflow.render(InquiryWorkflow.kt:43)
       at com.squareup.workflow1.internal.WorkflowNode.renderWithStateType(WorkflowNode.kt:188)
       at com.squareup.workflow1.internal.WorkflowNode.render(WorkflowNode.kt:103)
       at com.squareup.workflow1.internal.WorkflowChildNode.render(WorkflowChildNode.kt:55)
       at com.squareup.workflow1.internal.SubtreeManager.render(SubtreeManager.kt:130)
       at com.squareup.workflow1.internal.RealRenderContext.renderChild(RealRenderContext.kt:61)
       at com.squareup.workflow1.StatefulWorkflow$RenderContext.renderChild(StatefulWorkflow.kt:1)
       at com.squareup.workflow1.BaseRenderContext$DefaultImpls.renderChild$default(BaseRenderContext.kt:72)
       at com.withpersona.sdk2.inquiry.modal.ModalWorkflow.render(ModalWorkflow.kt:33)
       at com.withpersona.sdk2.inquiry.modal.ModalWorkflow.render(ModalWorkflow.kt:14)
       at com.squareup.workflow1.internal.WorkflowNode.renderWithStateType(WorkflowNode.kt:188)
       at com.squareup.workflow1.internal.WorkflowNode.render(WorkflowNode.kt:103)
       at com.squareup.workflow1.internal.WorkflowRunner.nextRendering(WorkflowRunner.kt:60)
       at com.squareup.workflow1.RenderWorkflowKt.renderWorkflowIn(RenderWorkflow.kt:118)
       at com.squareup.workflow1.ui.AndroidRenderWorkflowKt.renderWorkflowIn(AndroidRenderWorkflow.kt:255)
       at com.withpersona.sdk2.inquiry.internal.InquiryActivity$InquiryViewModel$renderings$2.invoke(InquiryActivity.kt:366)
       at com.withpersona.sdk2.inquiry.internal.InquiryActivity$InquiryViewModel$renderings$2.invoke(InquiryActivity.kt:365)
       at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
       at com.withpersona.sdk2.inquiry.internal.InquiryActivity$InquiryViewModel.getRenderings(InquiryActivity.kt:365)
       at com.withpersona.sdk2.inquiry.internal.InquiryActivity.onCreate(InquiryActivity.kt:225)
       at android.app.Activity.performCreate(Activity.java:8591)
       at android.app.Activity.performCreate(Activity.java:8570)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by jacoblange-dev** [comment]
thanks for the report, from our testing this is due to AGP 8 and we haven't yet released support for AGP 8. We have however already completed the upgrade and will release it sometime this week as `v2.9.0`.

**Comment by empowerDan** [comment]
Thank you!
